enc:

  size: [ 6.0, 4.5 ]
  origin: [ -85.0, 20.0 ]
  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  crs: "WGS84"
  S57_layers:
    "TSSLPT": "#8B0000"
    "CTNARE": "#964B00"
  resources: [ "data/db/US1GC09M" ]

  weather:
    PyThor_address: "http://127.0.0.1:5000"
    variables: [ "wave_direction",
                 "wave_height",
                 "wave_period",
                 "wind_direction",
                 "wind_speed",
                 "sea_current_speed",
                 "sea_current_direction",
                 "tide_height"
    ]



  # test config for FGDB

  #  size: [ 9000, 5062 ]
  #  center: [ 44300, 6956450 ]
  #  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  #  crs: "UTM33N"
  #  resources: [ "data/db/More_og_Romsdal_utm33.gdb" ]

  time:
    time_start: "24-09-2024 05:00"
    time_end: "24-09-2024 09:00"
    period: "hour"
    period_multiplier: 1


display:
  colorbar: False
  dark_mode: False
  fullscreen: False
  controls: True
  resolution: 640
  anchor: "center"
  dpi: 96



