enc:
  size: [ 6.0, 4.5 ]
  origin: [ -85.0, 20.0 ]
  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  crs: "WGS84"
  S57_layers:
    "TSSLPT": "#8B0000"
  resources: [ "data/db/US1GC09M" ]

  time:
    time_start: "24-09-2024 05:00"
    time_end: "24-09-2024 09:00"
    period: "hour"
    period_multiplier: 1

display:
  colorbar: False
  dark_mode: True
  fullscreen: False
  controls: True
  resolution: 640
  anchor: "center"
  dpi: 96



